version: '3.8'

networks:
  default:
    driver: bridge

services:
  registry:
    image: registry:2
    container_name: registry
    hostname: registry
    ports:
      - "5000:5000"
    volumes:
      - /home/morgan/certs:/certs:Z
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key

  webapp:
    build:
      context: ../webapp
      dockerfile: Dockerfile
    container_name: webapp
    hostname: webapp
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://webapp:8080/healthz"]
      interval: 1s
      timeout: 1s
      retries: 3
    depends_on:
      - registry

  balancer:
    image: nginx:alpine
    container_name: balancer
    hostname: balancer
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/morgan/certs:/etc/nginx/certs:ro
    depends_on:
      webapp:
        condition: service_healthy
